### ISSUE TITLE
Добавить CORS

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Files#4]
Сейчас фронта не могут тянуть ресурсы напрямую, надо бы сделать правильные CORS

И желательно - только на rtuitlab.dev домены. Штука опциональная, если хочется поиграться. Не думаю, что кто-то будет злоупотреблять

**Comment by Suput** [comment]
@CAPCHIK а где я могу увидеть, что корсы не работают?

**Comment by CAPCHIK** [comment]
У @baikinkirill

**Comment by Suput** [comment]
Пообщались. Говорит, что ему они больше не нужны, но ты всё равно хочешь, чтобы я это добавил, чтобы другие сервисы могли ходить в наши `files`

Я увидел подобное решение. Нормально будет?
```
server {

    root /path/to/your/stuff;

    index index.html index.htm;

     set $cors "";

    if ($http_origin ~* (.*\.yoursweetdomain.com)) {
        set $cors "true";
    }

    server_name yoursweetdomain.com;

    location / {

        if ($cors = "true") {
            add_header 'Access-Control-Allow-Origin' "$http_origin";
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE, PUT';
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Headers' 'User-Agent,Keep-Alive,Content-Type';
        }


        if ($request_method = OPTIONS) {
            return 204;
        }

    }
}
```

**Comment by CAPCHIK** [comment]
Ну похоже на правду, главное, чтобы работало

Проверить можно через F12 всегда 
![image](https://user-images.githubusercontent.com/12235437/156443945-2cd9e7bf-4d75-43d9-a071-222f7d4a6588.png)

**Comment by CAPCHIK** [comment]
Почти, но не совсем. Решил проверить с основного домена, и там не работает 😅
![image](https://user-images.githubusercontent.com/12235437/156714785-c08e8065-e2ee-4008-a8a6-8b6fa09c3249.png)

**Comment by Suput** [comment]
Я так и думал, что нужно это проверить) Потому что регулярка мне не нравилась. Понял, исправлю

**Comment by CAPCHIK** [comment]
По идее надо просто сделать `.+rtuitlab.dev` и все, вместо  `.+\.rtuitlab.dev`

**Comment by CAPCHIK** [comment]
Плюс только сейчас понял, что ничего кроме GET не нужно в CORS, ибо OPTIONS на GET не шлется, а менять контент мы не можем, так что можно просто отдавать GET
